# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Handleiding Zoeken in Onroerend Erfgoed Toepassingen'
copyright = '2022, Van Daele, Koen'
author = 'Van Daele, Koen'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.0.0'
# The full version, including alpha/beta/rc tags.
release = '1.0.0-alpha'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'sphinxcontrib.bibtex'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'nl'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_book_theme'

#import oe_sphinx_theme
#html_theme = 'oe_sphinx'
#html_theme_path = [oe_sphinx_theme.get_theme_dir()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Myst configuation --

myst_html_meta = {
    'citation_title': 'Zoeken in Onroerend Erfgoed toepassingen'
}

myst_enable_extensions = [
    'substitution'
]

# -- Bibtex configuration --

bibtex_bibfiles = ['citaties.bib']

# -- Latex configuration --

latex_engine = 'xelatex'

latex_documents = [
    ('latexindex', 'zoeken.tex',
    'Zoeken in Onroerend Erfgoed toepassingen',
    'Onroerend Erfgoed', 'manual')
]

latex_maketitle = r'''
\includepdf[pages=-]{./haoetest-1.pdf}
\includepdf[pages=-]{./haoetest-2.pdf}
\makeatletter
\begin{titlepage}
    \sphinxlogo
    \py@HeaderFamily
    \vspace*{\fill}
    \centering
    {\Huge \textcolor{OEpaars}{\textbf{\@title}} \par}
    {\itshape\LARGE \py@release\releaseinfo \par}
    \vfill
    {\LARGE
        \begin{tabular}[t]{c}
            \textsc{\@author}
        \end{tabular}\kern-\tabcolsep
    \par}
    \vfill\vfill
    {\large
        \@date \par
        \vfill
        \py@authoraddress \par
    }%
\end{titlepage}
'''

latex_extrapackages = r'''
\usepackage{pdfpages}
\usepackage{fontspec}
\usepackage{xcolor}
'''

latex_preamble = r'''
\setsansfont{FlandersArtSans-Regular}
%\newcommand\asteriskfill{\leavevmode\xleaders\hbox{$\ast\ $}\hfill\kern0pt}
\definecolor{OEpaars}{RGB}{117,63,127}
'''

latex_sphinxsetup = r'''%
TitleColor={RGB}{117,63,127}%
'''

latex_logo = 'Entiteitslogo_3regels_kleur_0.eps'

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'babel': '\\usepackage[dutch]{babel}',
    'extrapackages': latex_extrapackages,
    'maketitle': latex_maketitle,
    'preamble': latex_preamble,
    'sphinxsetup': latex_sphinxsetup
}
